// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNfEWzwF881mvJjZLVmoEQowYRzCwo61Y',
    appId: '1:1078484188114:web:c5c386f56a6a4d9b23260b',
    messagingSenderId: '1078484188114',
    projectId: 'wealthin-dfc1b',
    authDomain: 'wealthin-dfc1b.firebaseapp.com',
    storageBucket: 'wealthin-dfc1b.firebasestorage.app',
    measurementId: 'G-DZ7J04XDTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8pZ0JPqcK-3EOLEkHBhl-QvB53MS9ARY',
    appId: '1:1078484188114:android:59006e48f00fc14223260b',
    messagingSenderId: '1078484188114',
    projectId: 'wealthin-dfc1b',
    storageBucket: 'wealthin-dfc1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9uLhxOLZIGh1nk8Q5pUUiHgTY_ZEuq1I',
    appId: '1:1078484188114:ios:7078b7df9200965923260b',
    messagingSenderId: '1078484188114',
    projectId: 'wealthin-dfc1b',
    storageBucket: 'wealthin-dfc1b.firebasestorage.app',
    iosClientId:
        '1078484188114-cjrvbhbjupu3ako4b1bqs7uvvms6t3bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.wealthinFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9uLhxOLZIGh1nk8Q5pUUiHgTY_ZEuq1I',
    appId: '1:1078484188114:ios:7078b7df9200965923260b',
    messagingSenderId: '1078484188114',
    projectId: 'wealthin-dfc1b',
    storageBucket: 'wealthin-dfc1b.firebasestorage.app',
    iosClientId:
        '1078484188114-cjrvbhbjupu3ako4b1bqs7uvvms6t3bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.wealthinFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNfEWzwF881mvJjZLVmoEQowYRzCwo61Y',
    appId: '1:1078484188114:web:a1fb0898d7b1d08d23260b',
    messagingSenderId: '1078484188114',
    projectId: 'wealthin-dfc1b',
    authDomain: 'wealthin-dfc1b.firebaseapp.com',
    storageBucket: 'wealthin-dfc1b.firebasestorage.app',
    measurementId: 'G-LR479Z4BHG',
  );

  // Linux uses the same web configuration since Firebase doesn't have native Linux SDK
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDNfEWzwF881mvJjZLVmoEQowYRzCwo61Y',
    appId: '1:1078484188114:web:c5c386f56a6a4d9b23260b',
    messagingSenderId: '1078484188114',
    projectId: 'wealthin-dfc1b',
    authDomain: 'wealthin-dfc1b.firebaseapp.com',
    storageBucket: 'wealthin-dfc1b.firebasestorage.app',
    measurementId: 'G-DZ7J04XDTB',
  );
}
